blueprint:
  schedules:
    basic-job-creation-schedule: "*/1 * * * * *"
    basic-job-creation-ttl: 2
    basic-job-processing-interval: 4
spring:
  main:
    banner-mode: off
  cloud:
    stream:
      function:
        definition: basicjob-processor
        bindings:
          basicjob-processor-in-0: basicjobsIn
      bindings:
        basicjobsOut:
          destination: "Blueprint.Scheduled"
          group: "BasicJobs"
        basicjobsIn:
          destination: "Blueprint.Scheduled"
          group: "BasicJobs"
          consumer:
            max-attempts: 1
            concurrency: 1
            autoBindDlq: false
            exclusive: true
            singleActiveConsumer: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
