#spring:
#  cloud:
#    stream:
#      bindings:
#        persistentJobSupplier-out-0:
#          destination: Blueprint.Scheduled.Persistent
#          producer:
#            requiredGroups: MyJob
#        persistentjobProcessor-in-0:
#          destination: Blueprint.Scheduled.Persistent
#          group: MyJob
#          consumer:
#            max-attempts: 3
#            concurrency: 1
#            backOffInitialInterval: 2000
#            backOffMaxInterval: 10000
#        persistentjobProcessor-graveyard:
#          destination: Blueprint.Scheduled.Persistent.Graveyard
#          producer:
#            requiredGroups: MyJob
#      rabbit:
#        bindings:
#          persistentJobSupplier-out-0:
#            producer:
#              autobindDlq: true
#              dlqTtl: 5000
#              dlqDeadLetterExchange:
#          persistentjobProcessor-in-0:
#            consumer:
#              autoBindDlq: true
#              dlqTtl: 5000
#              dlqDeadLetterExchange:
#          persistentjobProcessor-graveyard:
#            producer:
#              autobindDlq: false
#              declareExchange: true

blueprint:
  persistent:
    schedules:
      persistent-job-creation-schedule: "* */1 * * * *"
      persistent-job-creation-ttl: 1
      persistent-job-processing-interval: 4

