spring:
  main:
    banner-mode: off
  application:
    name: blueprint
  profiles:
    include:
      - basicjob
      - persistentjob
      - batch
#  cloud:
#    stream:
#      function:
#        definition: basicjobProcessor;persistentjobProcessor;batchJobProcessor

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      ExternalParty:
        registerHealthIndicator: true
        slidingWindowSize: 5
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        failureRateThreshold: 1
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 30000
        slowCallDurationThreshold: 30000
        slowCallRateThreshold: 75
        allowHealthIndicatorToFail: true

server:
  port : 8081

logging.level.org.springframework.web: DEBUG

org.springframework.boot.actuate.health.Logger: DEBUG
logging.level.org.springframework.boot.actuate.health: DEBUG