
blueprint:
  basicjob:
    schedules:
      basic-job-creation-schedule: "*/2 * * * * *"
      basic-job-creation-ttl: 1
      basic-job-batch-creation-schedule: "*/10 * * * * *"
      basic-job-batch-creation-ttl: 4
      basic-job-processing-interval: 4

