spring:
  main:
    banner-mode: off
  application:
    name: blueprint

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      ExternalParty:
        registerHealthIndicator: true
        slidingWindowSize: 5
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        failureRateThreshold: 1
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 30000
        slowCallDurationThreshold: 30000
        slowCallRateThreshold: 75
        allowHealthIndicatorToFail: true

server:
  port : 8081


blueprint:
  basicjob:
    schedules:
      basic-job-creation-schedule: "*/2 * * * * *"
      basic-job-creation-ttl: 1
      basic-job-batch-creation-schedule: "*/10 * * * * *"
      basic-job-batch-creation-ttl: 4
  batch:
    schedules:
      basic-job-processing-interval: 4
      batch-creation-schedule: "* */1 * * * *"
  persistent:
    schedules:
      persistent-job-creation-schedule: "* */1 * * * *"
      persistent-job-creation-ttl: 1
      persistent-job-processing-interval: 4

logging.level.org.springframework.web: DEBUG

org.springframework.boot.actuate.health.Logger: DEBUG
logging.level.org.springframework.boot.actuate.health: DEBUG