spring:
  main:
    banner-mode: off
  application:
    name: blueprint
  profiles:
    include:
      - basicjobs
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
